import io, os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm
from fastapi.responses import StreamingResponse

def build_invoice_pdf(supplier:str, month:str, items, fee_rate=0.01):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4

    pink = (1, 0, 0.5)
    purple = (0.196, 0.141, 0.275)

    c.setFillColor(pink); c.setFont("Helvetica-Bold", 18)
    c.drawString(20*mm, (H-20*mm), "INFINITE GZ SDN. BHD.")
    c.setFillColor(purple); c.setFont("Helvetica", 12)
    c.drawString(20*mm, (H-28*mm), f"Supplier Invoice · {supplier}")
    c.drawString(20*mm, (H-34*mm), f"Period: {month}")

    y = H-48*mm
    c.setFillColorRGB(1,1,1)
    c.setStrokeColor(purple)
    c.setFillColor(purple)
    c.rect(20*mm, y, W-40*mm, 8*mm, fill=1, stroke=0)
    c.setFillColorRGB(1,1,1); c.setFont("Helvetica-Bold", 10)
    c.drawString(22*mm, y+2.5*mm, "Date")
    c.drawString(60*mm, y+2.5*mm, "Description")
    c.drawRightString(W-42*mm, y+2.5*mm, "Amount (RM)")
    y -= 10*mm

    total = 0.0
    c.setFillColorRGB(1,1,1); c.setStrokeColor(purple)
    c.setFont("Helvetica", 10)
    for it in items:
        if y < 30*mm:
            c.showPage(); y = H-20*mm
        c.setFillColorRGB(1,1,1)
        c.rect(20*mm, y, W-40*mm, 8*mm, fill=0, stroke=1)
        c.setFillColorRGB(1,1,1)
        c.drawString(22*mm, y+2.5*mm, str(it.get("date","")))
        c.drawString(60*mm, y+2.5*mm, str(it.get("desc",""))[:40])
        c.drawRightString(W-42*mm, y+2.5*mm, f'{float(it.get("amount",0.0)):.2f}')
        total += float(it.get("amount",0.0))
        y -= 9*mm

    fee = total * float(os.getenv("SERVICE_FEE_RATE", fee_rate))
    grand = total + fee

    y -= 5*mm
    c.setFont("Helvetica-Bold", 11); c.setFillColor(pink)
    c.drawRightString(W-42*mm, y, f"Subtotal: RM {total:.2f}")
    y -= 6*mm; c.drawRightString(W-42*mm, y, f"Service Fee ({int(float(os.getenv('SERVICE_FEE_RATE','0.01'))*100)}%): RM {fee:.2f}")
    y -= 6*mm; c.drawRightString(W-42*mm, y, f"Total Due: RM {grand:.2f}")

    c.setFillColor(purple); c.setFont("Helvetica-Oblique", 9)
    c.drawString(20*mm, 15*mm, "This invoice is generated by CreditPilot · INFINITE GZ SDN. BHD.")

    c.showPage(); c.save()
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/pdf",
           headers={"Content-Disposition": f'attachment; filename="invoice_{supplier}_{month}.pdf"'})
